name: MobilePlugin
version: '${project.version}'
main: de.capitain_america.mobileplugin.MobilePlugin
api-version: '1.21'
commands:
  inv:
    description: Öffnet das Inventar anderer Spieler
  ec:
    description: Open your Enderchest
  vanish:
    description: Schaltet Vanish an oder aus.
